import React from "react";
import { WizardStep } from "../../hooks/useNewWorkflowState";
import { WorkflowBasicFields } from "@/components/workflows/WorkflowBasicFields";
import { TemplateEditor } from "@/components/workflows/TemplateEditor";
import { FormFieldsEditor } from "@/components/workflows/FormFieldsEditor";

interface WizardFormStepProps {
  setStep: (step: WizardStep) => void;
  workflowForm: any;
  handleSubmit: (e: React.FormEvent) => void;
  submission: any;
  validation: any;
  error: string | null;
}

export const WizardFormStep: React.FC<WizardFormStepProps> = ({
  setStep,
  workflowForm,
  handleSubmit,
  submission,
  validation,
  error,
}) => {
  return (
    <div className="max-w-5xl mx-auto">
      <div className="mb-8">
        <button
          onClick={() => setStep("choice")}
          className="text-sm text-gray-500 hover:text-gray-700 dark:text-muted-foreground dark:hover:text-foreground mb-4 flex items-center gap-1 transition-colors group"
        >
          <span className="group-hover:-translate-x-1 transition-transform">
            ←
          </span>
          Start Over
        </button>
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold text-gray-900 dark:text-foreground">
              {workflowForm.formData.workflow_name || "New Workflow"}
            </h1>
            <p className="text-gray-600 dark:text-muted-foreground mt-1">
              Configure your lead magnet workflow details
            </p>
          </div>
          <button
            onClick={handleSubmit}
            disabled={submission.isSubmitting || !validation.valid}
            className="px-6 py-2.5 bg-blue-600 text-white rounded-lg font-medium hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors shadow-sm"
          >
            {submission.isSubmitting ? "Creating..." : "Create Workflow"}
          </button>
        </div>
      </div>

      {error && (
        <div className="mb-6 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 text-red-700 dark:text-red-400 px-4 py-3 rounded-lg">
          {error}
        </div>
      )}

      <div className="grid gap-8">
        <section className="bg-white dark:bg-card rounded-lg shadow-sm border border-gray-200 dark:border-border overflow-hidden">
          <div className="p-6 border-b border-gray-200 dark:border-border bg-gray-50/50 dark:bg-gray-900/50">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-foreground">
              Basic Information
            </h2>
            <p className="text-sm text-gray-500 dark:text-muted-foreground">
              General settings for your workflow
            </p>
          </div>
          <div className="p-6">
            <WorkflowBasicFields
              formData={workflowForm.formData}
              onChange={workflowForm.updateFormData}
            />
          </div>
        </section>

        <section className="bg-white dark:bg-card rounded-lg shadow-sm border border-gray-200 dark:border-border overflow-hidden">
          <div className="p-6 border-b border-gray-200 dark:border-border bg-gray-50/50 dark:bg-gray-900/50">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-foreground">
              Input Form
            </h2>
            <p className="text-sm text-gray-500 dark:text-muted-foreground">
              Define the fields users need to fill out
            </p>
          </div>
          <div className="p-6">
            <FormFieldsEditor
              formFieldsData={workflowForm.formFieldsData}
              onChange={workflowForm.updateFormFieldsData}
              onFieldChange={workflowForm.updateFormField}
              onAddField={workflowForm.addFormField}
              onRemoveField={workflowForm.removeFormField}
            />
          </div>
        </section>

        <section className="bg-white dark:bg-card rounded-lg shadow-sm border border-gray-200 dark:border-border overflow-hidden">
          <div className="p-6 border-b border-gray-200 dark:border-border bg-gray-50/50 dark:bg-gray-900/50">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-foreground">
              Content Template
            </h2>
            <p className="text-sm text-gray-500 dark:text-muted-foreground">
              Design the content generated by this workflow
            </p>
          </div>
          <div className="p-6">
            <TemplateEditor
              templateData={workflowForm.templateData}
              onChange={workflowForm.updateTemplateData}
            />
          </div>
        </section>
      </div>
    </div>
  );
};
