import {
  ArrowDownIcon,
  ArrowDownTrayIcon,
  ArrowLeftIcon,
  ArrowLeftOnRectangleIcon,
  ArrowPathIcon,
  ArrowRightIcon,
  ArrowRightOnRectangleIcon,
  ArrowTopRightOnSquareIcon,
  ArrowUpIcon,
  ArrowUpTrayIcon,
  ArrowUturnLeftIcon,
  ArrowUturnRightIcon,
  ArrowsPointingInIcon,
  ArrowsPointingOutIcon,
  ArrowsUpDownIcon,
  Bars3BottomLeftIcon,
  BoltIcon,
  CameraIcon,
  ChartBarIcon,
  ChatBubbleLeftRightIcon,
  CheckBadgeIcon,
  CheckCircleIcon,
  ClipboardDocumentIcon,
  ChevronDoubleRightIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CircleStackIcon,
  ClockIcon,
  CodeBracketIcon,
  Cog6ToothIcon,
  CommandLineIcon,
  ComputerDesktopIcon,
  CpuChipIcon,
  CubeIcon,
  CurrencyDollarIcon,
  CursorArrowRaysIcon,
  DevicePhoneMobileIcon,
  DeviceTabletIcon,
  DocumentArrowDownIcon,
  DocumentIcon,
  DocumentTextIcon,
  EnvelopeIcon,
  EyeIcon,
  ExclamationCircleIcon,
  ExclamationTriangleIcon,
  FilmIcon,
  FunnelIcon,
  GlobeAltIcon,
  HashtagIcon,
  HomeIcon,
  InboxIcon,
  LinkIcon,
  ListBulletIcon,
  MagnifyingGlassIcon,
  MinusCircleIcon,
  PaperAirplaneIcon,
  PauseIcon,
  PencilSquareIcon,
  PhoneIcon,
  PhotoIcon,
  PlayIcon,
  PlusIcon,
  PresentationChartLineIcon,
  RectangleGroupIcon,
  ServerStackIcon,
  ShieldCheckIcon,
  Square3Stack3DIcon,
  StopCircleIcon,
  TrashIcon,
  UserIcon,
  UsersIcon,
  VariableIcon,
  ViewColumnsIcon,
  XCircleIcon,
  XMarkIcon,
} from "@heroicons/react/24/outline";
import { CheckIcon } from "@heroicons/react/20/solid";

export {
  ExclamationTriangleIcon as FiAlertTriangle,
  CodeBracketIcon as FiCode,
  CommandLineIcon as FiTerminal,
  UserIcon as FiUser,
  Cog6ToothIcon as FiSettings,
  ArrowRightOnRectangleIcon as FiLogOut,
  ChevronDownIcon as FiChevronDown,
  XMarkIcon as FiX,
  UsersIcon as FiUsers,
  FunnelIcon as FiFilter,
  EyeIcon as FiEye,
  PlusIcon as FiPlus,
  TrashIcon as FiTrash2,
  DocumentArrowDownIcon as FiSave,
  ExclamationCircleIcon as FiAlertCircle,
  ArrowPathIcon as FiLoader,
  ClipboardDocumentIcon as FiCopy,
  CheckIcon as FiCheck,
  ChevronUpIcon as FiChevronUp,
  PencilSquareIcon as FiEdit,
  CpuChipIcon as FiCpu,
  GlobeAltIcon as FiGlobe,
  CubeIcon as FiBox,
  ChatBubbleLeftRightIcon as FiMessageSquare,
  DocumentTextIcon as FiFileText,
  PhotoIcon as FiImage,
  ComputerDesktopIcon as FiMonitor,
  BoltIcon as FiZap,
  Bars3BottomLeftIcon as FiAlignLeft,
  RectangleGroupIcon as FiLayout,
  LinkIcon as FiLink,
  ArrowsPointingOutIcon as FiMaximize2,
  ArrowLeftIcon as FiArrowLeft,
  MagnifyingGlassIcon as FiSearch,
  PencilSquareIcon as FiEdit2,
  ShieldCheckIcon as FiShield,
  CheckBadgeIcon as FiUserCheck,
  ArrowLeftOnRectangleIcon as FiLogIn,
  ArrowPathIcon as FiRefreshCw,
  CheckCircleIcon as FiCheckCircle,
  ClockIcon as FiClock,
  ArrowTopRightOnSquareIcon as FiExternalLink,
  XCircleIcon as FiXCircle,
  ArrowRightIcon as FiArrowRight,
  PlayIcon as FiPlay,
  ArrowUturnLeftIcon as FiRotateCcw,
  ChevronDoubleRightIcon as FiSkipForward,
  ArrowUpTrayIcon as FiUpload,
  CommandLineIcon as FiCommand,
  HomeIcon as FiHome,
  ListBulletIcon as FiList,
  ChartBarIcon as FiBarChart2,
  ChevronRightIcon as FiChevronRight,
  PresentationChartLineIcon as FiActivity,
  CursorArrowRaysIcon as FiMousePointer,
  CircleStackIcon as FiDatabase,
  ArrowsPointingInIcon as FiMinimize2,
  ArrowDownTrayIcon as FiDownload,
  ViewColumnsIcon as FiSidebar,
  PauseIcon as FiPause,
  DocumentIcon as FiFile,
  DeviceTabletIcon as FiTablet,
  DevicePhoneMobileIcon as FiSmartphone,
  FilmIcon as FiFilm,
  CameraIcon as FiCamera,
  EnvelopeIcon as FiMail,
  PhoneIcon as FiPhone,
  HashtagIcon as FiHash,
  VariableIcon as FiType,
  InboxIcon as FiInbox,
  PaperAirplaneIcon as FiSend,
  CurrencyDollarIcon as FiDollarSign,
  Square3Stack3DIcon as FiLayers,
  ChevronLeftIcon as FiChevronLeft,
  ArrowUpIcon as FiArrowUp,
  ArrowDownIcon as FiArrowDown,
  MinusCircleIcon as FiCircle,
  StopCircleIcon as FiStopCircle,
  ArrowsUpDownIcon as FiMove,
  ArrowUturnRightIcon as FiRotateCw,
  ServerStackIcon as FiHardDrive,
};
